services:
    medi:
      build: .
      ports:
        - '80:80'
      container_name: Medicontainer
      volumes:
        - myapp:/var/www/html/
      network_mode: 
          bridge
volumes:
   myapp: