services:
    oxer:
    Healet:
      build: .
      ports:
        - '80:80' '81:81'
      container_names: oxercontainer-boxer 
                       Healetcontainer
      volumes:
        - myapp:/var/www/html/
      network_mode: 
          bridge

volumes:
   myapp: