services:
    oxer:
      build: .
      ports:
        - '80:80'
      container_name: oxercontainer-boxer
      volumes:
        - myapp:/var/www/html/
      network_mode: 
          bridge

volumes:
    myapp:
    Healet:
      build: .
      container_name: healetcontainer
      volumes:
        - myapp:/var/www/html/
      network_mode: 
          bridge