services:
    medi:
      build: .
      ports:
        - '80:80'
      container_name: Medicontainer
      volumes:
        - myapp2:/var/www/html/
      network_mode: 
          bridge

    healet:
      build: ./health/
      ports:
        - '81:80'
      container_name: Healetcontainer
      volumes:
        - myapp3:/var/www/html/
      network_mode: 
          bridge

    traffic-light:
      build: ./microservices/traffic-light/
      ports:
        - '82:80'
      container_name: trafficcontainer
      volumes:
        - myapp4:/var/www/html/
      network_mode: 
          bridge
volumes:
   myapp3:
   myapp2:
   myapp4:

