services:
    oxer:
      build: .
      ports:
        - '80:80'
      container_names: oxercontainer-boxer
      volumes:
        - myapp:/var/www/html/
      network_mode: 
          bridge

volumes:
   myapp: