services:
    Healet:
      build: .
      ports:
        - '80:80'
      container_name: healetcontainer
      volumes:
        - myapp:/var/www/html/
      network_mode: 
          bridge

volumes:
   myapp: