services:
    oxer:
      build: .
      ports:
        - '80:80'
      container_name: oxercontainer
      volumes:
        - myapp:/var/www/html/
      network_mode: 
          bridge
volumes:
   myapp: