services:
    counter:
      build: ./counter/
      ports:
        - '81:80'
      container_name: counter-container
      volumes:
        - myapp1:/var/www/html/
      network_mode: 
          bridge


    index:
      build: ./index/
      ports:
        - '80:80'
      container_name: index-container
      volumes:
        - myapp2:/var/www/html/
      network_mode: 
          bridge


    number-add:
      build: ./number-addition/
      ports:
        - '82:80'
      container_name: number-add-container
      volumes:
        - myapp3:/var/www/html/
      network_mode: 
          bridge


    puppy:
      build: ./puppy/
      ports:
        - '83:80'
      container_name: puppy-container
      volumes:
        - myapp4:/var/www/html/
      network_mode: 
          bridge


    season:
      build: ./season-switcher/
      ports:
        - '84:80'
      container_name: season-container
      volumes:
        - myapp5:/var/www/html/
      network_mode: 
          bridge


    todo:
      build: ./todo6/
      ports:
        - '85:80'
      container_name: todo-container
      volumes:
        - myapp6:/var/www/html/
      network_mode: 
          bridge


    traffic:
      build: ./traffic-light/
      ports:
        - '86:80'
      container_name: traffic-container
      volumes:
        - myapp7:/var/www/html/
      network_mode: 
          bridge


    vr-website:
      build: ./Vr-website/
      ports:
        - '87:80'
      container_name: vr-website-container
      volumes:
        - myapp8:/var/www/html/
      network_mode: 
          bridge

    mycodingprofileRWD:
      build: ./mycodingprofileRWD/
      ports:
        - '88:80'
      container_name: mycodingprofileRWD-container
      volumes:
        - myapp9:/var/www/html/
      network_mode: 
          bridge

volumes:
   myapp1:
   myapp2:
   myapp3:
   myapp4:
   myapp5:
   myapp6:
   myapp7:
   myapp8:
   myapp9: